name: 06 Add Alpha Profile
on:
  workflow_dispatch:
    inputs:
      newProfileId:
        description: 'New Profile ID'
        required: true
        default: 0
        type: number
jobs:
  add-alpha-profile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        run: npm install
      - name: Add Alpha Profile
        run: NEW_PROFILE_ID=${{ inputs.newProfileId }} npm run add-alpha-profile
      - name: Commit
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git pull
          git add .
          git commit -m "Add Alpha Profile"
          git push