name: Get Images
on:
  workflow_dispatch:
jobs:
  get-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        run: npm install
      - name: Get Images
        run: npm run get-images
      - name: Commit
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git pull
          git add .
          git commit -m "Get Images"
          git push