name: Process Profiles
on:
  workflow_dispatch:
jobs:
  process-profiles:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        run: npm install
      - name: Process Profiles
        run: npm run process-profiles
      - name: Commit
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git pull
          git status
          git add .
          git commit -m "Process Profiles"
          git push