name: Process Opponents
on:
  workflow_dispatch:
jobs:
  process-opponents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        run: npm install
      - name: Process Opponents
        run: npm run process-opponents
      - name: Commit
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git pull
          git status
          git add .
          git commit -m "Process Opponents"
          git push