name: Data Scrape
on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 4"
jobs:
  data-scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm i
      - name: Scrape Data
        run: npm run scrape
      - name: Commit File Changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git pull
          git status
          git add .
          git commit -m "Data Scrape"
          git push