name: Data Scrape
on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 4"
jobs:
  data-scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        run: npm install
      - name: Scrape
        run: npm run scrape
      - name: Commit
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git pull
          git status
          git add .
          git commit -m "Data Scrape"
          git push