name: Data Scrape
on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 4"
jobs:
  data-scrape:
    runs-on: ubuntu-latest
    container: node:latest
    steps:
      - uses: actions/checkout@v4
      - run: |
        npm install
        npm audit
        npm run scrape
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git pull
        git status
        git add .
        git commit -m "Data Scrape"
        git push